# Generated by Django 5.2.7 on 2025-10-23 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IG', 'Instagram'), ('TIKTOK', 'TikTok'), ('BOTH', 'Both')], max_length=10)),
                ('media_type', models.CharField(choices=[('SINGLE_IMAGE', 'Single Image'), ('CAROUSEL', 'Carousel'), ('VIDEO', 'Video')], max_length=20)),
                ('media_file', models.FileField(upload_to='media/')),
                ('schedule_time', models.DateTimeField()),
                ('needs_ai_edit', models.BooleanField(default=False)),
                ('ai_edit_prompt', models.TextField(blank=True, null=True)),
                ('needs_ai_caption', models.BooleanField(default=False)),
                ('final_caption', models.TextField(blank=True, null=True)),
                ('upload_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
