# Generated by Django 5.2.7 on 2025-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='content_type',
            field=models.CharField(blank=True, choices=[('REELS', 'Reels'), ('STORIES', 'Stories'), ('SINGLE_POST', 'Single Post'), ('CAROUSEL_POST', 'Carousel Post'), ('TIKTOK_VIDEO', 'TikTok Video')], max_length=20, null=True),
        ),
    ]
