# Generated by Django 4.2.25 on 2025-10-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_schedule_media_file_mediaasset_apischedulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ai_caption_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
