# Generated by Django 4.2.25 on 2025-10-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_schedule_ai_caption_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='final_caption',
            new_name='ai_generated_caption',
        ),
        migrations.AddField(
            model_name='schedule',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved')], default='PENDING_APPROVAL', max_length=20),
        ),
    ]
