# Generated by Django 4.2.25 on 2025-10-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_rename_final_caption_schedule_ai_generated_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ai_caption_prompt',
        ),
    ]
