# Generated by Django 4.2.25 on 2025-10-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_schedule_ai_caption_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Preview'), ('CONFIRMED', 'Confirmed & Processing'), ('SCHEDULED', 'Scheduled')], default='PENDING_APPROVAL', max_length=20),
        ),
    ]
