# Generated by Django 4.2.25 on 2025-10-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='edited_file',
            field=models.FileField(blank=True, null=True, upload_to='media/edited/'),
        ),
    ]
