# Generated by Django 4.2.25 on 2025-10-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_mediaasset_edited_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content_type',
            field=models.CharField(blank=True, choices=[('REELS', 'Reels'), ('STORIES', 'Stories'), ('IMAGES', 'Single / Carousel Post'), ('TIKTOK_VIDEO', 'TikTok Video')], max_length=20, null=True),
        ),
    ]
