# Generated by Django 4.2.25 on 2025-10-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_schedule_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='media_type',
            field=models.CharField(choices=[('SINGLE_IMAGE', 'Image(s)'), ('VIDEO', 'Video')], max_length=20),
        ),
    ]
