# Generated by Django 4.2.25 on 2025-10-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_schedule_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content_type',
            field=models.CharField(blank=True, choices=[('REELS', 'Reels'), ('STORIES', 'Stories'), ('IMAGES', 'Single / Carousel Post')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image(s)'), ('VIDEO', 'Video')], max_length=20),
        ),
    ]
