# Generated by Django 4.2.25 on 2025-10-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_schedule_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content_type',
            field=models.CharField(blank=True, choices=[('STORIES', 'Stories'), ('REELS', 'Reels'), ('FEEDS', 'Feeds')], max_length=20, null=True),
        ),
    ]
