# Generated by Django 4.2.25 on 2025-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_schedule_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('BOTH', 'Both')], max_length=10),
        ),
    ]
